Src/GMS.Web.Admin/Areas/ToolManage/Controllers/FullLifeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using GMS.Web.Admin.Common;
using GMS.Account.Contract;
using GMS.ToolManage.Contract;

namespace GMS.Web.Admin.Areas.ToolManage.Controllers
{
    [Permission(EnumBusinessPermission.ToolManage_Information)]
    public class FullLifeController : AdminControllerBase
    {
        //
        // GET: /ToolManage/FullLife/

        public ActionResult Index(int id, FullLifeIndex pageIndex)
        {
            var model = this.ToolManageService.GetFullLife(id, pageIndex);
            return View(model);
        }

        public ActionResult In(int id, int pageIndex = 1)
        {
            var page = new FullLifeIndex();
            page.pageIndex1 = pageIndex;
            var model = this.ToolManageService.GetFullLife(id, page);
            return View(model);
        }

        public ActionResult Out(int id, int pageIndex = 1)
        {
            var page = new FullLifeIndex();
            page.pageIndex2 = pageIndex;
            var model = this.ToolManageService.GetFullLife(id, page);
            return View(model);
        }

        public ActionResult Repair(int id, int pageIndex = 1)
        {
            var page = new FullLifeIndex();
            page.pageIndex5 = pageIndex;
            var model = this.ToolManageService.GetFullLife(id, page);
            return View(model);
        }

        public ActionResult Warehouse(int id, int pageIndex = 1)
        {
            var page = new FullLifeIndex();
            page.pageIndex3 = pageIndex;
            var model = this.ToolManageService.GetFullLife(id, page);
            return View(model);
        }

        public ActionResult Scrap(int id, int pageIndex = 1)
        {
            var page = new FullLifeIndex();
            page.pageIndex4 = pageIndex;
            var model = this.ToolManageService.GetFullLife(id, page);
            return View(model);
        }

        public ActionResult Index_old(int id, FullLifeIndex pageIndex)
        {
            var model = this.ToolManageService.GetFullLife(id, pageIndex);
            return View(model);
        }
    }
}

Src/GMS.Web.Admin/Areas/ToolManage/Controllers/InController.cs
using System.Web;
using System.Web.Mvc;
using GMS.Web.Admin.Common;
using GMS.ToolManage.Contract;
using GMS.Account.Contract;
using GMS.Framework.Utility;
using GMS.Framework.Contract;
using System;

namespace GMS.Web.Admin.Areas.ToolManage.Controllers
{
    public class InController : AdminControllerBase
    {
        //
        // GET: /ToolManage/In/

        public ActionResult Index(InTableRequest request)//入库
        {
            request.Workcell = LoginInfo.Workcell;
            var result = this.ToolManageService.GetInTableList(request);
            return View(result);
        }
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create(FormCollection formCollection)
        {
            var Data = new InTable();
            this.TryUpdateModel(Data);
            Data.WarehousingDate = DateTime.Now;
            Data.Workcell = LoginInfo.Workcell;
            ToolManageService.SaveInTable(Data);
            return RedirectToAction("Index");
        }

    }
}

Src/GMS.Web.Admin/Areas/ToolManage/Controllers/ManagerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using GMS.Web.Admin.Common;
using GMS.Account.Contract;
using GMS.ToolManage.Contract;

namespace GMS.Web.Admin.Areas.ToolManage.Controllers
{
    
    public class ManagerController : AdminControllerBase
    {
        //
        // GET: /ToolManage/Manage/
        [Permission(EnumBusinessPermission.ToolManage_Manager)]
        public ActionResult Out(OutTableRequest request)//出库管理
        {
            var result = this.ToolManageService.GetOutTableList(request);
            return View(result);
        }
        [Permission(EnumBusinessPermission.ToolManage_Manager)]
        public ActionResult Out_Create()
        {
            var model = new OutTable();
            return View(model);
        }
        [Permission(EnumBusinessPermission.ToolManage_Manager)]
        public ActionResult Out_Edit(int id)
        {
            var model = this.ToolManageService.GetOutTable(id);
            return View(model);
        }
        [Permission(EnumBusinessPermission.ToolManage_Manager)]
        [HttpPost]
        public ActionResult Out_Create(object message)
        {
            var model = new OutTable();
            this.TryUpdateModel<OutTable>(model);
            //model.OutTableDate = DateTime.Now;
            this.ToolManageService.SaveOutTable(model);
            return this.RefreshParent();
        }
        [Permission(EnumBusinessPermission.ToolManage_Manager)]
        [HttpPost]
        public ActionResult Out_Edit(OutTable Data)
        {
            this.ToolManageService.SaveOutTable(Data);
            return this.RefreshParent();
        }
        [Permission(EnumBusinessPermission.ToolManage_Manager)]
        [HttpPost]
        public ActionResult Out_Delete(List<int> ids)
        {
            this.ToolManageService.DeleteOutTable(ids);
            return this.RedirectToAction("Out");
        }
        [Permission(EnumBusinessPermission.ToolManage_Manager)]
        public ActionResult In(InTableRequest request)//入库管理
        {
            var result = this.ToolManageService.GetInTableList(request);
            return View(result);
        }
        [Permission(EnumBusinessPermission.ToolManage_Manager)]
        public ActionResult In_Create()
        {
            var model = new tongs_entity();
            return View(model);
        }
        [Permission(EnumBusinessPermission.ToolManage_Manager)]
        public ActionResult In_Edit(int id)
        {
            var model = this.ToolManageService.Gettongs_entity(id);
            return View(model);
        }
        [Permission(EnumBusinessPermission.ToolManage_Manager)]
        [HttpPost]
        public ActionResult In_Create(object message)
        {
            var model = new tongs_entity();
            this.TryUpdateModel<tongs_entity>(model);
            model.RegDate = DateTime.Now;
            this.ToolManageService.Savetongs_entity(model);
            return this.RefreshParent();
        }
        [Permission(EnumBusinessPermission.ToolManage_Manager)]
        [HttpPost]
        public ActionResult In_Edit(tongs_entity Data)
        {
            this.ToolManageService.Savetongs_entity(Data);
            return this.RefreshParent();
        }
        [Permission(EnumBusinessPermission.ToolManage_Manager)]
        [HttpPost]
        public ActionResult In_Delete(List<int> ids)
        {
            this.ToolManageService.Deletetongs_entity(ids);
            return this.RedirectToAction("In");
        }
        [Permission(EnumBusinessPermission.ToolManage_Manager)]
        public ActionResult Repair(tongs_entityRequest request)//报修管理
        {
            var result = this.ToolManageService.Gettongs_entityList(request);
            return View(result);
        }
        [Permission(EnumBusinessPermission.ToolManage_Manager)]
        public ActionResult Repair_Create()
        {
            var model = new tongs_entity();
            return View(model);
        }
        [Permission(EnumBusinessPermission.ToolManage_Manager)]
        public ActionResult Repair_Edit(int id)
        {
            var model = this.ToolManageService.Gettongs_entity(id);
            return View(model);
        }
        [Permission(EnumBusinessPermission.ToolManage_Manager)]
        [HttpPost]
        public ActionResult Repair_Create(object message)
        {
            var model = new tongs_entity();
            this.TryUpdateModel<tongs_entity>(model);
            model.RegDate = DateTime.Now;
            this.ToolManageService.Savetongs_entity(model);
            return this.RefreshParent();
        }
        [Permission(EnumBusinessPermission.ToolManage_Manager)]
        [HttpPost]
        public ActionResult Repair_Edit(tongs_entity Data)
        {
            this.ToolManageService.Savetongs_entity(Data);
            return this.RefreshParent();
        }
        [Permission(EnumBusinessPermission.ToolManage_Manager)]
        [HttpPost]
        public ActionResult Repair_Delete(List<int> ids)
        {
            this.ToolManageService.Deletetongs_entity(ids);
            return this.RedirectToAction("Repair");
        }
        [Permission(EnumBusinessPermission.ToolManage_Information)]
        public ActionResult Information(tongs_entityRequest request)//信息查询
        {
            request.Workcell = LoginInfo.Workcell;
            var result = this.ToolManageService.Gettongs_entityList(request);
            return View(result);
        }
        [Permission(EnumBusinessPermission.ToolManage_Information)]
        public ActionResult Information_Create()
        {
            var model = new tongs_entity();
            return View(model);
        }
        [Permission(EnumBusinessPermission.ToolManage_Information)]
        public ActionResult Information_Edit(int id)
        {
            var model = this.ToolManageService.Gettongs_entity(id);
            return View(model);
        }
        [Permission(EnumBusinessPermission.ToolManage_Information)]
        [HttpPost]
        public ActionResult Information_Create(object message)
        {
            var model = new tongs_entity();
            this.TryUpdateModel<tongs_entity>(model);
            model.RegDate = DateTime.Now;
            model.Workcell = LoginInfo.Workcell;
            this.ToolManageService.Savetongs_entity(model);
            return this.RefreshParent();
        }
        [Permission(EnumBusinessPermission.ToolManage_Information)]
        [HttpPost]
        public ActionResult Information_Edit(tongs_entity Data)
        {
            var ImagePath = Data.ImagePath;
            if (ImagePath != null)
            {
                string filename = DateTime.Now.Ticks + ImagePath.FileName;
                string truepath = Server.MapPath(@"/Upload/");
                string filepath = truepath + filename;
                string urlfilepath = @"/Upload/" + filename;
                ImagePath.SaveAs(filepath);
                Data.Photo = urlfilepath;
            }
            else
            {
                Data.Photo = ToolManageService.Gettongs_entity(Data.ID).Photo;
            }
            this.ToolManageService.Savetongs_entity(Data);
            return this.RefreshParent();
        }
        [Permission(EnumBusinessPermission.ToolManage_Information)]
        [HttpPost]
        public ActionResult Information_Delete(List<int> ids)
        {
            this.ToolManageService.Deletetongs_entity(ids);
            return this.RedirectToAction("Information");
        }
    }
}

Src/GMS.Web.Admin/Areas/ToolManage/Controllers/OutController.cs
using System.Web;
using System.Web.Mvc;
using GMS.Web.Admin.Common;
using GMS.ToolManage.Contract;
using GMS.Account.Contract;
using GMS.Framework.Utility;
using GMS.Framework.Contract;
using System;

namespace GMS.Web.Admin.Areas.ToolManage.Controllers
{
    public class OutController : AdminControllerBase
    {
        //
        // GET: /ToolManage/Out/

        public ActionResult Index(OutTableRequest request)//出库
        {
            request.Workcell = LoginInfo.Workcell;
            var result = this.ToolManageService.GetOutTableList(request);
            return View(result);
        }
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create(OutTable Data)
        {
            Data.OutstorageDate = DateTime.Now;
            Data.Workcell = LoginInfo.Workcell;
            ToolManageService.SaveOutTable(Data);
            return RedirectToAction("Out");
        }

    }
}

Src/GMS.Web.Admin/Areas/ToolManage/Controllers/RepairController.cs
using System.Web;
using System.Web.Mvc;
using GMS.Web.Admin.Common;
using GMS.ToolManage.Contract;
using GMS.Account.Contract;
using GMS.Framework.Utility;
using GMS.Framework.Contract;
using System;

namespace GMS.Web.Admin.Areas.ToolManage.Controllers
{
    public class RepairController : AdminControllerBase
    {
        public ActionResult Index(RepairTableRequest request)//报修
        {
            request.Workcell = LoginInfo.Workcell;
            var model = this.ToolManageService.GetRepairTableList(request);
            return View(model);
        }
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create(RepairTable Data)
        {
            Data.CreateTime = DateTime.Now;
            Data.MaintainDate = DateTime.Now;
            Data.Workcell = LoginInfo.Workcell;
            ToolManageService.SaveRepairTable(Data);
            return RedirectToAction("Index");
        }

    }
}

Src/GMS.Web.Admin/Areas/ToolManage/Views/Manager/Information.cshtml
@using GMS.Framework.Contract
@using GMS.Framework.Utility
@using GMS.Framework.Web.Controls
@using GMS.ToolManage.Contract

@model PagedList<tongs_entity>
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section PageSpecificStyleSheetIncludes{
    <!-- BEGIN PAGE LEVEL STYLES -->
    <link rel="stylesheet" type="text/css" href="/assets/global/plugins/select2/select2.css" />
    <link rel="stylesheet" type="text/css" href="/assets/global/plugins/datatables/extensions/Scroller/css/dataTables.scroller.min.css" />
    <link rel="stylesheet" type="text/css" href="/assets/global/plugins/datatables/extensions/ColReorder/css/dataTables.colReorder.min.css" />
    <link rel="stylesheet" type="text/css" href="/assets/global/plugins/datatables/plugins/bootstrap/dataTables.bootstrap.css" />
    <!-- END PAGE LEVEL STYLES -->
}

<div class="portlet box blue">
    <div class="portlet-title">
        <div class="caption">
            <i class="fa fa-list"></i> 工夹具记录
        </div>
        <div class="tools">
            <a href="javascript:;" class="collapse" data-original-title="" title=""></a>
        </div>
    </div>
    <div class="portlet-body">
        <table class="table table-striped table-bordered table-hover dataTable no-footer" role="grid">
            <thead>
                <tr>
                    <th style="width: 8px;">
                        <input type="checkbox" id="checkall" class="group-checkable" />
                    </th>
                    <th>
                        夹具代码
                    </th>
                    <th>
                        夹具系列号
                    </th>
                    <th>
                        采购单据号
                    </th>
                    <th>
                        入库日期
                    </th>
                    <th>
                        存放库位
                    </th>
                    <th>
                        状态
                    </th>
                    <th>
                        已使用次数
                    </th>
                    <th>
                        故障概率
                    </th>
                    <th>
                        操作
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var m in Model)
                {
                    <tr>
                        <td>
                            <input type="checkbox" class="checkboxes" name='ids' value='@m.ID' />
                        </td>
                        <td>
                            @m.Code
                        </td>
                        <td>
                            @m.SeqID
                        </td>
                        <td>
                            @m.BillNo
                        </td>
                        <td>
                            @m.RegDate.ToString("yyyy-MM-dd HH-mm-ss")
                        </td>
                        <td>
                            @m.Location-@m.Bin
                        </td>
                        <td>
                            @m.State
                        </td>
                        <td>
                            @m.UsedCount
                        </td>
                        <td>
                            @m.ErrProbability
                        </td>
                        <td>
                            <a class="btn btn-xs purple" title='查看工夹具全寿命信息' href="@Url.Action("Index","FullLife", new { id = m.ID })">
                                <i class="fa fa-list"></i> 全寿命
                            </a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
        <div class="row">
            <div class="col-md-5 col-sm-12">
                <div class="dataTables_info" role="status" aria-live="polite">
                    Total : @Model.TotalItemCount entries
                </div>
            </div>
            @if (Model.TotalPageCount > 1)
            {
                <div class="col-md-7 col-sm-12">
                    <div class="dataTables_paginate paging_simple_numbers">
                        <ul class="pagination">
                            @if (Model.CurrentPageIndex == 1)
                            {
                                <li class="paginate_button previous disabled" aria-controls="sample_1" tabindex="0"><a href="#"><i class="fa fa-angle-left"></i></a></li>
                            }
                            else
                            {
                                <li class="paginate_button previous" aria-controls="sample_1" tabindex="0" id="sample_1_previous"><a href="?pageIndex=@(Model.CurrentPageIndex-1)"><i class="fa fa-angle-left"></i></a></li>
                            }
                            @if (Model.TotalPageCount <= 5)
                            {
                                for (int i = 1; i <= Model.TotalPageCount; ++i)
                                {
                                    if (i == Model.CurrentPageIndex)
                                    {
                                        <li class="paginate_button active" aria-controls="sample_1" tabindex="0"><a href="?pageIndex=@i">@i</a></li>
                                    }
                                    else
                                    {
                                        <li class="paginate_button" aria-controls="sample_1" tabindex="0"><a href="?pageIndex=@i">@i</a></li>
                                    }
                                }
                            }
                            else
                            {
                                if (Model.TotalPageCount - 5 >= Model.CurrentPageIndex)
                                {
                                    for (int i = Model.CurrentPageIndex; i < Model.CurrentPageIndex + 4; ++i)
                                    {
                                        if (i == Model.CurrentPageIndex)
                                        {
                                            <li class="paginate_button active" aria-controls="sample_1" tabindex="0"><a href="?pageIndex=@i">@i</a></li>
                                        }
                                        else
                                        {
                                            <li class="paginate_button" aria-controls="sample_1" tabindex="0"><a href="?pageIndex=@i">@i</a></li>
                                        }
                                    }
                                    <li class="paginate_button disabled" aria-controls="sample_1" tabindex="0"><a href="">...</a></li>
                                }
                                else
                                {
                                    for (int i = Model.TotalPageCount - 4; i <= Model.TotalPageCount; ++i)
                                    {
                                        if (i == Model.CurrentPageIndex)
                                        {
                                            <li class="paginate_button active" aria-controls="sample_1" tabindex="0"><a href="?pageIndex=@i">@i</a></li>
                                        }
                                        else
                                        {
                                            <li class="paginate_button" aria-controls="sample_1" tabindex="0"><a href="?pageIndex=@i">@i</a></li>
                                        }
                                    }
                                }
                            }
                            @if (Model.CurrentPageIndex == Model.TotalPageCount)
                            {
                                <li class="paginate_button disabled" aria-controls="sample_1" tabindex="0" id="sample_1_next"><a href="#"><i class="fa fa-angle-right"></i></a></li>
                            }
                            else
                            {
                                <li class="paginate_button" aria-controls="sample_1" tabindex="0" id="sample_1_next"><a href="?pageIndex=@(Model.CurrentPageIndex+1)"><i class="fa fa-angle-right"></i></a></li>
                            }
                        </ul>
                    </div>
                </div>
            }
        </div>
    </div>
</div>

Src/GMS.Web.Admin/Areas/ToolManage/Views/Manager/Information_Create.cshtml
@using GMS.Framework.Contract
@using GMS.Framework.Web.Controls
@using GMS.Account.Contract
@using GMS.ToolManage.Contract;

@model tongs_entity
@{
    Layout = "~/Views/Shared/_Layout.Edit.cshtml";
}

@{
    <div class="portlet-body form-horizontal form-bordered form-row-stripped">
        <div class="row-fluid">


            <div class="control-group">
                <label class="control-label"><span class="required">*</span>代码：</label>
                <div class="controls">
                    @Html.TextBoxFor(m => m.Code, new { @class = "m-wrap" })
                    <span class="help-inline">@Html.ValidationMessageFor(m => m.Code)</span>
                </div>
            </div>
            <div class="control-group">
                <label class="control-label"><span class="required">*</span>系列号：</label>
                <div class="controls">
                    @Html.TextBoxFor(m => m.SeqID, new { @class = "m-wrap" })
                    <span class="help-inline">@Html.ValidationMessageFor(m => m.SeqID)</span>
                </div>
            </div>
            <div class="control-group">
                <label class="control-label"><span class="required">*</span>模块：</label>
                <div class="controls">
                    @Html.TextBoxFor(m => m.Model, new { @class = "m-wrap" })
                    <span class="help-inline">@Html.ValidationMessageFor(m => m.Model)</span>
                </div>
            </div>
            <div class="control-group">
                <label class="control-label"><span class="required">*</span>夹具料号：</label>
                <div class="controls">
                    @Html.TextBoxFor(m => m.PartNo, new { @class = "m-wrap" })
                    <span class="help-inline">@Html.ValidationMessageFor(m => m.PartNo)</span>
                </div>
            </div>
            <div class="control-group">
                <label class="control-label"><span class="required">*</span>采购单据号：</label>
                <div class="controls">
                    @Html.TextBoxFor(m => m.BillNo, new { @class = "m-wrap" })
                    <span class="help-inline">@Html.ValidationMessageFor(m => m.BillNo)</span>
                </div>
            </div>
            <div class="control-group">
                <label class="control-label"><span class="required">*</span>存放库位：</label>
                <div class="controls">
                    @Html.TextBoxFor(m => m.Location, new { @class = "m-wrap" })
                    <span class="help-inline">@Html.ValidationMessageFor(m => m.Location)</span>
                </div>
            </div>
            <div class="control-group">
                <label class="control-label"><span class="required">*</span>代码：</label>
                <div class="controls">
                    @Html.TextBoxFor(m => m.Bin, new { @class = "m-wrap" })
                    <span class="help-inline">@Html.ValidationMessageFor(m => m.Bin)</span>
                </div>
            </div>
            <div class="control-group">
                <label class="control-label"><span class="required">*</span>状态：</label>
                <div class="controls">
                    @Html.TextBoxFor(m => m.State, new { @class = "m-wrap" })
                    <span class="help-inline">@Html.ValidationMessageFor(m => m.State)</span>
                </div>
            </div>
            <div class="control-group">
                <label class="control-label"><span class="required">*</span>图片：</label>
                <div class="controls">
                    @Html.TextBoxFor(m => m.Photo, new { @class = "m-wrap" })
                    <span class="help-inline">@Html.ValidationMessageFor(m => m.Photo)</span>
                </div>
            </div>
            <div class="control-group">
                <label class="control-label"><span class="required">*</span>已使用次数：</label>
                <div class="controls">
                    @Html.TextBoxFor(m => m.UsedCount, new { @class = "m-wrap" })
                    <span class="help-inline">@Html.ValidationMessageFor(m => m.UsedCount)</span>
                </div>
            </div>
            <div class="control-group">
                <label class="control-label"><span class="required">*</span>故障概率：</label>
                <div class="controls">
                    @Html.TextBoxFor(m => m.ErrProbability, new { @class = "m-wrap" })
                    <span class="help-inline">@Html.ValidationMessageFor(m => m.ErrProbability)</span>
                </div>
            </div>

        </div>
    </div>
}

Src/GMS.Web.Admin/Areas/ToolManage/Views/Manager/Information_Edit.cshtml
@using GMS.Framework.Contract
@using GMS.Framework.Web.Controls
@using GMS.Account.Contract
@using GMS.ToolManage.Contract;

@model tongs_entity
@{
    Layout = "~/Views/Shared/_Layout.Edit.cshtml";
}

@{
    <div class="portlet-body form-horizontal form-bordered form-row-stripped">
        <div class="row-fluid">

            <div class="control-group">
                <label class="control-label"><span class="required">*</span>代码：</label>
                <div class="controls">
                    @Html.TextBoxFor(m => m.Code, new { @class = "m-wrap" })
                    <span class="help-inline">@Html.ValidationMessageFor(m => m.Code)</span>

                </div>
            </div>
            <div class="control-group">
                <label class="control-label"><span class="required">*</span>模块：</label>
                <div class="controls">
                    @Html.TextBoxFor(m => m.Model, new { @class = "m-wrap" })
                    <span class="help-inline">@Html.ValidationMessageFor(m => m.Model)</span>
                </div>
            </div>
            <div class="control-group">
                <label class="control-label"><span class="required">*</span>夹具料号：</label>
                <div class="controls">
                    @Html.TextBoxFor(m => m.PartNo, new { @class = "m-wrap" })
                    <span class="help-inline">@Html.ValidationMessageFor(m => m.PartNo)</span>
                </div>
            </div>
            <div class="control-group">
                <label class="control-label"><span class="required">*</span>采购单据号：</label>
                <div class="controls">
                    @Html.TextBoxFor(m => m.BillNo, new { @class = "m-wrap" })
                    <span class="help-inline">@Html.ValidationMessageFor(m => m.BillNo)</span>
                </div>
            </div>
            <div class="control-group">
                <label class="control-label"><span class="required">*</span>入库日期：</label>
                <div class="controls">
                    @Html.TextBoxFor(m => m.RegDate, "{0:yyyy-MM-dd hh:mm:ss}", new { @class = "m-wrap" })
                    <span class="help-inline">@Html.ValidationMessageFor(m => m.RegDate)</span>
                </div>
            </div>
            <div class="control-group">
                <label class="control-label"><span class="required">*</span>存放库位：</label>
                <div class="controls">
                    @Html.TextBoxFor(m => m.Location, new { @class = "m-wrap" })
                    <span class="help-inline">@Html.ValidationMessageFor(m => m.Location)</span>
                </div>
            </div>
            <div class="control-group">
                <label class="control-label"><span class="required">*</span>代码：</label>
                <div class="controls">
                    @Html.TextBoxFor(m => m.Bin, new { @class = "m-wrap" })
                    <span class="help-inline">@Html.ValidationMessageFor(m => m.Bin)</span>
                </div>
            </div>
            <div class="control-group">
                <label class="control-label"><span class="required">*</span>状态：</label>
                <div class="controls">
                    @Html.TextBoxFor(m => m.State, new { @class = "m-wrap" })
                    <span class="help-inline">@Html.ValidationMessageFor(m => m.State)</span>
                </div>
            </div>
            <div class="control-group">
                <label class="control-label">图片：</label>
                <div class="controls">
                    <img id="ImageShow" src="@Model.Photo" alt="无法正常显示" height=192 /><br>
                    <input class="m-wrap" id="ImagePath" name="ImagePath" type="file" onchange="uploadImg();" />
                    <!--<span class="help-inline">Html.ValidationMessageFor(m => m.Photo)</span>-->
                </div>
            </div>
            <div class="control-group">
                <label class="control-label"><span class="required">*</span>已使用次数：</label>
                <div class="controls">
                    @Html.TextBoxFor(m => m.UsedCount, new { @class = "m-wrap" })
                    <span class="help-inline">@Html.ValidationMessageFor(m => m.UsedCount)</span>
                </div>
            </div>
            <div class="control-group">
                <label class="control-label"><span class="required">*</span>故障概率：</label>
                <div class="controls">
                    @Html.TextBoxFor(m => m.ErrProbability, new { @class = "m-wrap" })
                    <span class="help-inline">@Html.ValidationMessageFor(m => m.ErrProbability)</span>
                </div>
            </div>

        </div>
    </div>
}
<script>
    function uploadImg() {
        var fd = new FormData();
        fd.append("ImagePath", $('#ImagePath')[0].files[0]);
        $.ajax({
            url: '/Home/UploadImg',
            type: 'post',
            processData: false,
            contentType: false,
            data: fd,
            success: function (data) {
                $('#ImageShow').attr("src", data);
            }

        })
        //$('#ImagePath').attr("accept", "");
    }
</script>